// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBy4XniEUmEtXUBKHhdnqrDTYjIMKSkxY',
    appId: '1:780268495815:web:4e8c0d2760b9b004a8afe2',
    messagingSenderId: '780268495815',
    projectId: 'mijinitech-ab0a8',
    authDomain: 'mijinitech-ab0a8.firebaseapp.com',
    storageBucket: 'mijinitech-ab0a8.appspot.com',
    measurementId: 'G-6HHP8MVYDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBns8yWeBlY8_K5hTh6qpqzXsPPtdPLlP8',
    appId: '1:780268495815:android:7ee59bc3492ee335a8afe2',
    messagingSenderId: '780268495815',
    projectId: 'mijinitech-ab0a8',
    storageBucket: 'mijinitech-ab0a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8ACPjddSSmvLDLR6LSioCYs-J2KkIcQ',
    appId: '1:780268495815:ios:d810568e11012e13a8afe2',
    messagingSenderId: '780268495815',
    projectId: 'mijinitech-ab0a8',
    storageBucket: 'mijinitech-ab0a8.appspot.com',
    iosClientId: '780268495815-qvtk9fbapqh95u1v5afgd01vaa9tfblu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mijini',
  );
}
